### ISSUE TITLE
Show type on hover

### ISSUE THREAD

**Issue by andywhite37** [Sketch-sh/nit#2]
Not sure if this is possible or feasible, but it would be amazing if you could see the type of a variable on hover, like how you can see errors on hover.  I know getting the compilation error info from the compiler output is different than getting type info, so feel free to close if this is way out of scope.

**Comment by thangngoc89** [comment]
Thank you for your suggestion. Though this is a realy hard feature so I'll put this in the back log

**Comment by andywhite37** [comment]
No problem - you can just close it if you don't think it will ever happen - I know this is a huge can of worms.

**Comment by thangngoc89** [comment]
@andywhite37 yeah. I have to agree on that. 

FYI, for displaying type information, you need to somehow send the `typed_tree` here to the editor 

https://github.com/thangngoc89/bucklescript/blob/f7c7771ca31d0bd8054787c51296f9159440774d/jscomp/main/jsoo_main.ml#L129
