### ISSUE TITLE
Visual feedback that there are parsing issues.

### ISSUE THREAD

**Issue by cristianoc** [Sketch-sh/nit#4]
Was curious whether this was based on bucklescript 5.x or 6.x.
So tried: `type t = | A {x:int};`.
The lack of output is an indication that something went wrong, but one could be more explicit.

**Comment by thangngoc89** [comment]
Thank you for reporting this. apparently nit crashed with your code so no visual feedbacks are provided. I'll look into this.

And this is based on bucklescript 5.x
